apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: podman-desktop-image-checker-openshift-ext
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: podman-desktop-image-checker-openshift-ext
    app.kubernetes.io/part-of: podman-desktop-image-checker-openshift-ext
  name: podman-desktop-image-checqhro
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: podman-desktop-image-checker-openshift-ext
    weight: 100
status: {}
