apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: podman-desktop-image-checker-openshift-ext
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: podman-desktop-image-checker-openshift-ext
    app.kubernetes.io/part-of: podman-desktop-image-checker-openshift-ext
  name: podman-desktop-image-checker-openshift-ext
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: podman-desktop-image-checker-openshift-ext
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: podman-desktop-image-checker-openshift-ext
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/phmartin-tenant/podman-desktop-image-checker-openshift-ext/podman-desktop-image-checker-openshift-ext@sha256:97bde69f2ed8e049131aac43c63a995e136fcea717ce6d4536d15f83bc448e81
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
