apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: podman-desktop-image-checker-openshift-ext
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: podman-desktop-image-checker-openshift-ext
    app.kubernetes.io/part-of: podman-desktop-image-checker-openshift-ext
  name: podman-desktop-image-checker-openshift-ext
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: podman-desktop-image-checker-openshift-ext
status:
  loadBalancer: {}
